version: '3'

volumes:
  prometheus_data: {}

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-nft-price-eth
    volumes:
      - ../../../mongodb/nft-price-eth/:/data/db/
    ports:
      - '27017:27017'

  prometheus:
    image: prom/prometheus
    volumes:
      - ../../config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    restart: always

  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4510-4559:4510-4559' # external service port range
      - '127.0.0.1:4566:4566' # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=docker-reuse
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - HOSTNAME_EXTERNAL=host.docker.internal
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - mongodb
      - prometheus
      - pushgateway
